import Foundation
import Testing

@testable import FSRS

// MARK: - Long sequence byte-parity vs ts-fsrs reference
//
// The existing parity suite (`ts-fsrs parity` in FSRSTests.swift) only
// pins three steps of an all-Good Sequence A. This file extends the byte-
// parity contract over LONG mixed-rating sequences (50+ steps) in both
// scheduler modes, plus a handful of targeted edge scenarios.
//
// Reference values were generated by /tmp/fsrs_ref.py + /tmp/sim_fsrs.py,
// which reproduce ts-fsrs algorithm.ts and basic_scheduler.ts /
// long_term_scheduler.ts exactly. Both reference scripts are validated
// against ts-fsrs' own FSRS-6.test.ts (`ivl_history` and `memory state`
// tests reproduce to all 8 rounded decimals).
//
// Timing convention: every review fires at `card.due`. With Swift's
// `refDate = 06:13:20 UTC` and the scheduler computing `due = lastReview
// + scheduledDays * 86400`, the time-of-day stays fixed across reviews,
// so `Card.elapsedDays(now:)` returns exactly `card.scheduledDays` UTC-day
// crossings — matching the integer `t` the reference passes to
// `next_state`.
//
// All numeric assertions use exact `==` (no tolerance). The point of this
// suite is to prove byte-identical S/D, scheduledDays, reps, and lapses
// across long sequences — divergence at any step is a real bug and the
// failing test should be left in place to localise it.

/// One row of a reference trajectory: rating to apply at that step, plus
/// the expected post-review card state.
private struct Step {
    let rating: Rating
    let stability: Double
    let difficulty: Double
    let scheduledDays: Int
    let reps: Int
    let lapses: Int
}

/// Drives a card through `steps` using `fsrs`, reviewing each time at the
/// card's current `due` date. Asserts every observable field at every step.
///
/// Splitting the loop into a helper keeps the assertion logic identical
/// across all sequences (so a parity break can be diagnosed by reading
/// one helper, not 50 inlined #expect calls).
private func runSequence(
    label: String,
    fsrs: FSRS,
    initialCard: Card = FSRS.createCard(now: refDate),
    initialNow: Date = refDate,
    steps: [Step],
    sourceLocation: SourceLocation = #_sourceLocation
) {
    var card = initialCard
    var now = initialNow
    for (i, step) in steps.enumerated() {
        let humanIndex = i + 1  // 1-indexed for failure messages
        card = fsrs.schedule(card: card, now: now, rating: step.rating).card
        #expect(
            card.stability == step.stability,
            "[\(label)] step \(humanIndex) (\(step.rating)): stability \(card.stability) ≠ expected \(step.stability)",
            sourceLocation: sourceLocation
        )
        #expect(
            card.difficulty == step.difficulty,
            "[\(label)] step \(humanIndex) (\(step.rating)): difficulty \(card.difficulty) ≠ expected \(step.difficulty)",
            sourceLocation: sourceLocation
        )
        #expect(
            card.scheduledDays == step.scheduledDays,
            "[\(label)] step \(humanIndex) (\(step.rating)): scheduledDays \(card.scheduledDays) ≠ expected \(step.scheduledDays)",
            sourceLocation: sourceLocation
        )
        #expect(
            card.reps == step.reps,
            "[\(label)] step \(humanIndex) (\(step.rating)): reps \(card.reps) ≠ expected \(step.reps)",
            sourceLocation: sourceLocation
        )
        #expect(
            card.lapses == step.lapses,
            "[\(label)] step \(humanIndex) (\(step.rating)): lapses \(card.lapses) ≠ expected \(step.lapses)",
            sourceLocation: sourceLocation
        )
        now = card.due
    }
}

// MARK: - Mixed 50-step sequence (basic + long-term modes)

/// SHA-256-derived deterministic rating sequence: rating_i = (sha256("42_i")[0] % 4) + 1.
/// Reproducible from any language: `python3 -c "import hashlib;
/// [print((hashlib.sha256(f'42_{i}'.encode()).digest()[0] % 4) + 1) for i in range(50)]"`.
///
/// The 50-rating sequence below was generated by /tmp/gen_swift_data.py,
/// which uses the same Python helper to ensure the rating list and the
/// expected trajectory are produced together (no human transcription).
@Suite("Long sequence parity — mixed 50 reviews")
struct LongSequenceParityTests {

    // MARK: - 50-step basic mode
    //
    // Reference: /tmp/sim_fsrs.py (validated against ts-fsrs FSRS-6.test.ts
    // `ivl_history`). Default learning steps [60s, 600s], relearning [600s].
    // Sequence runs through every state transition — new → learning →
    // review → relearning → review — including in-day short-term reviews
    // and multi-lapse runs.
    @Test("50-review mixed sequence in basic mode (enableShortTerm: true)")
    func basicMixed50() {
        let fsrs = FSRS()  // defaults: enableShortTerm = true, no fuzz
        let steps: [Step] = [
            Step(rating: .good, stability: 2.30650000, difficulty: 2.11810397, scheduledDays: 0, reps: 1, lapses: 0),
            Step(rating: .hard, stability: 2.30650000, difficulty: 4.75285849, scheduledDays: 0, reps: 2, lapses: 0),
            Step(rating: .good, stability: 2.30650000, difficulty: 4.74333400, scheduledDays: 2, reps: 3, lapses: 0),
            Step(rating: .easy, stability: 13.72899634, difficulty: 2.97202955, scheduledDays: 14, reps: 4, lapses: 0),
            Step(rating: .again, stability: 1.68606235, difficulty: 7.67518227, scheduledDays: 0, reps: 5, lapses: 1),
            Step(rating: .hard, stability: 1.68606235, difficulty: 8.44190603, scheduledDays: 0, reps: 6, lapses: 1),
            Step(rating: .again, stability: 0.57839294, difficulty: 9.47309348, scheduledDays: 0, reps: 7, lapses: 1),
            Step(rating: .again, stability: 0.21288563, difficulty: 9.81203778, scheduledDays: 0, reps: 8, lapses: 1),
            Step(rating: .good, stability: 0.24765179, difficulty: 9.79745411, scheduledDays: 1, reps: 9, lapses: 1),
            Step(rating: .again, stability: 0.11077337, difficulty: 9.91865291, scheduledDays: 0, reps: 10, lapses: 2),
            Step(rating: .good, stability: 0.13452366, difficulty: 9.90396263, scheduledDays: 1, reps: 11, lapses: 2),
            Step(rating: .good, stability: 0.46657587, difficulty: 9.88928704, scheduledDays: 2, reps: 12, lapses: 2),
            Step(rating: .hard, stability: 0.91688969, difficulty: 9.91173195, scheduledDays: 1, reps: 13, lapses: 2),
            Step(rating: .good, stability: 1.49683963, difficulty: 9.89704859, scheduledDays: 2, reps: 14, lapses: 2),
            Step(rating: .again, stability: 0.42792511, difficulty: 9.95138894, scheduledDays: 0, reps: 15, lapses: 3),
            Step(rating: .hard, stability: 0.42792511, difficulty: 9.95295808, scheduledDays: 0, reps: 16, lapses: 3),
            Step(rating: .again, stability: 0.16065765, difficulty: 9.96976601, scheduledDays: 0, reps: 17, lapses: 3),
            Step(rating: .again, stability: 0.06433255, difficulty: 9.97529067, scheduledDays: 0, reps: 18, lapses: 3),
            Step(rating: .good, stability: 0.08096982, difficulty: 9.96054375, scheduledDays: 1, reps: 19, lapses: 3),
            Step(rating: .good, stability: 0.32875960, difficulty: 9.94581158, scheduledDays: 2, reps: 20, lapses: 3),
            Step(rating: .again, stability: 0.15310472, difficulty: 9.96741701, scheduledDays: 0, reps: 21, lapses: 4),
            Step(rating: .hard, stability: 0.15310472, difficulty: 9.96359826, scheduledDays: 0, reps: 22, lapses: 4),
            Step(rating: .hard, stability: 0.15310472, difficulty: 9.96106320, scheduledDays: 0, reps: 23, lapses: 4),
            Step(rating: .easy, stability: 0.31311815, difficulty: 9.93328071, scheduledDays: 1, reps: 24, lapses: 4),
            Step(rating: .hard, stability: 0.58141693, difficulty: 9.94093700, scheduledDays: 1, reps: 25, lapses: 4),
            Step(rating: .easy, stability: 1.55873819, difficulty: 9.90642927, scheduledDays: 3, reps: 26, lapses: 4),
            Step(rating: .hard, stability: 2.34838476, difficulty: 9.92311176, scheduledDays: 2, reps: 27, lapses: 4),
            Step(rating: .again, stability: 0.55834128, difficulty: 9.95995573, scheduledDays: 0, reps: 28, lapses: 5),
            Step(rating: .hard, stability: 0.55834128, difficulty: 9.95864512, scheduledDays: 0, reps: 29, lapses: 5),
            Step(rating: .again, stability: 0.20598300, difficulty: 9.97163531, scheduledDays: 0, reps: 30, lapses: 5),
            Step(rating: .hard, stability: 0.20598300, difficulty: 9.96639857, scheduledDays: 0, reps: 31, lapses: 5),
            Step(rating: .again, stability: 0.08114447, difficulty: 9.97418380, scheduledDays: 0, reps: 32, lapses: 5),
            Step(rating: .easy, stability: 0.17303008, difficulty: 9.95078560, scheduledDays: 1, reps: 33, lapses: 5),
            Step(rating: .good, stability: 0.52675441, difficulty: 9.93606318, scheduledDays: 2, reps: 34, lapses: 5),
            Step(rating: .hard, stability: 0.97704612, difficulty: 9.94278413, scheduledDays: 1, reps: 35, lapses: 5),
            Step(rating: .hard, stability: 1.31863962, difficulty: 9.94724581, scheduledDays: 1, reps: 36, lapses: 5),
            Step(rating: .hard, stability: 1.66895125, difficulty: 9.95020768, scheduledDays: 2, reps: 37, lapses: 5),
            Step(rating: .again, stability: 0.45693464, difficulty: 9.96886197, scheduledDays: 0, reps: 38, lapses: 6),
            Step(rating: .easy, stability: 0.86961615, difficulty: 9.94368546, scheduledDays: 1, reps: 39, lapses: 6),
            Step(rating: .good, stability: 1.42845210, difficulty: 9.92897014, scheduledDays: 2, reps: 40, lapses: 6),
            Step(rating: .easy, stability: 3.26119442, difficulty: 9.89046364, scheduledDays: 4, reps: 41, lapses: 6),
            Step(rating: .again, stability: 0.72217096, difficulty: 9.94922451, scheduledDays: 0, reps: 42, lapses: 7),
            Step(rating: .again, stability: 0.26195045, difficulty: 9.96853882, scheduledDays: 0, reps: 43, lapses: 7),
            Step(rating: .good, stability: 0.30059897, difficulty: 9.95379865, scheduledDays: 1, reps: 44, lapses: 7),
            Step(rating: .easy, stability: 1.10943005, difficulty: 9.92358868, scheduledDays: 3, reps: 45, lapses: 7),
            Step(rating: .good, stability: 2.29229920, difficulty: 9.90889346, scheduledDays: 3, reps: 46, lapses: 7),
            Step(rating: .hard, stability: 3.14256293, difficulty: 9.92474760, scheduledDays: 3, reps: 47, lapses: 7),
            Step(rating: .good, stability: 4.59754545, difficulty: 9.91005122, scheduledDays: 5, reps: 48, lapses: 7),
            Step(rating: .easy, stability: 8.75915764, difficulty: 9.86522289, scheduledDays: 9, reps: 49, lapses: 7),
            Step(rating: .hard, stability: 11.04640908, difficulty: 9.89575704, scheduledDays: 11, reps: 50, lapses: 7),
        ]
        runSequence(label: "basic50", fsrs: fsrs, steps: steps)
    }

    // MARK: - 50-step long-term mode
    //
    // Same rating sequence as basicMixed50, run through LongTermScheduler.
    // Every review goes straight to Review state, no learning steps. The
    // S/D values diverge from basic mode because (a) the lapse path uses
    // `postLapseFloor = s` instead of `s / exp(w[17] * w[18])`, and (b)
    // every review (even t=0) routes through recall/forget formulas, not
    // the short-term formula.
    //
    // Lapses also increment differently here: LongTermScheduler bumps
    // `lapses` for Again on any non-new prior state (including Learning/
    // Relearning, which don't exist in this mode but the predicate still
    // catches every Again after the first review).
    @Test("50-review mixed sequence in long-term mode (enableShortTerm: false)")
    func longTermMixed50() {
        let fsrs = FSRS(parameters: Parameters(enableShortTerm: false))
        let steps: [Step] = [
            Step(rating: .good, stability: 2.30650000, difficulty: 2.11810397, scheduledDays: 3, reps: 1, lapses: 0),
            Step(rating: .hard, stability: 9.23487052, difficulty: 4.75285849, scheduledDays: 9, reps: 2, lapses: 0),
            Step(rating: .good, stability: 30.30415925, difficulty: 4.74333400, scheduledDays: 30, reps: 3, lapses: 0),
            Step(rating: .easy, stability: 137.90247564, difficulty: 2.97202955, scheduledDays: 138, reps: 4, lapses: 0),
            Step(rating: .again, stability: 4.35030269, difficulty: 7.67518227, scheduledDays: 4, reps: 5, lapses: 1),
            Step(rating: .hard, stability: 7.80302929, difficulty: 8.44190603, scheduledDays: 8, reps: 6, lapses: 1),
            Step(rating: .again, stability: 1.18730803, difficulty: 9.47309348, scheduledDays: 1, reps: 7, lapses: 2),
            Step(rating: .again, stability: 0.34166761, difficulty: 9.81203778, scheduledDays: 1, reps: 8, lapses: 3),
            Step(rating: .good, stability: 0.85211468, difficulty: 9.79745411, scheduledDays: 3, reps: 9, lapses: 3),
            Step(rating: .again, stability: 0.31836410, difficulty: 9.91865291, scheduledDays: 1, reps: 10, lapses: 4),
            Step(rating: .good, stability: 0.77298372, difficulty: 9.90396263, scheduledDays: 3, reps: 11, lapses: 4),
            Step(rating: .good, stability: 1.84621270, difficulty: 9.88928704, scheduledDays: 3, reps: 12, lapses: 4),
            Step(rating: .hard, stability: 2.67816341, difficulty: 9.91173195, scheduledDays: 3, reps: 13, lapses: 4),
            Step(rating: .good, stability: 4.12178252, difficulty: 9.89704859, scheduledDays: 5, reps: 14, lapses: 4),
            Step(rating: .again, stability: 0.83393002, difficulty: 9.95138894, scheduledDays: 1, reps: 15, lapses: 5),
            Step(rating: .hard, stability: 1.16553317, difficulty: 9.95295808, scheduledDays: 2, reps: 16, lapses: 5),
            Step(rating: .again, stability: 0.36616945, difficulty: 9.96976601, scheduledDays: 1, reps: 17, lapses: 6),
            Step(rating: .again, stability: 0.14862432, difficulty: 9.97529067, scheduledDays: 1, reps: 18, lapses: 7),
            Step(rating: .good, stability: 0.47281867, difficulty: 9.96054375, scheduledDays: 3, reps: 19, lapses: 7),
            Step(rating: .good, stability: 1.31509843, difficulty: 9.94581158, scheduledDays: 3, reps: 20, lapses: 7),
            Step(rating: .again, stability: 0.41802437, difficulty: 9.96741701, scheduledDays: 1, reps: 21, lapses: 8),
            Step(rating: .hard, stability: 0.70068674, difficulty: 9.96359826, scheduledDays: 2, reps: 22, lapses: 8),
            Step(rating: .hard, stability: 1.18151665, difficulty: 9.96106320, scheduledDays: 2, reps: 23, lapses: 8),
            Step(rating: .easy, stability: 2.89562461, difficulty: 9.93328071, scheduledDays: 4, reps: 24, lapses: 8),
            Step(rating: .hard, stability: 3.94250818, difficulty: 9.94093700, scheduledDays: 4, reps: 25, lapses: 8),
            Step(rating: .easy, stability: 7.32968782, difficulty: 9.90642927, scheduledDays: 7, reps: 26, lapses: 8),
            Step(rating: .hard, stability: 9.13274730, difficulty: 9.92311176, scheduledDays: 9, reps: 27, lapses: 8),
            Step(rating: .again, stability: 1.27155837, difficulty: 9.95995573, scheduledDays: 1, reps: 28, lapses: 9),
            Step(rating: .hard, stability: 1.61667062, difficulty: 9.95864512, scheduledDays: 2, reps: 29, lapses: 9),
            Step(rating: .again, stability: 0.44823562, difficulty: 9.97163531, scheduledDays: 1, reps: 30, lapses: 10),
            Step(rating: .hard, stability: 0.73495118, difficulty: 9.96639857, scheduledDays: 2, reps: 31, lapses: 10),
            Step(rating: .again, stability: 0.27085109, difficulty: 9.97418380, scheduledDays: 1, reps: 32, lapses: 11),
            Step(rating: .easy, stability: 1.03694819, difficulty: 9.95078560, scheduledDays: 4, reps: 33, lapses: 11),
            Step(rating: .good, stability: 2.34545536, difficulty: 9.93606318, scheduledDays: 3, reps: 34, lapses: 11),
            Step(rating: .hard, stability: 3.17763533, difficulty: 9.94278413, scheduledDays: 3, reps: 35, lapses: 11),
            Step(rating: .hard, stability: 4.03903618, difficulty: 9.94724581, scheduledDays: 4, reps: 36, lapses: 11),
            Step(rating: .hard, stability: 5.12332042, difficulty: 9.95020768, scheduledDays: 5, reps: 37, lapses: 11),
            Step(rating: .again, stability: 0.92456174, difficulty: 9.96886197, scheduledDays: 1, reps: 38, lapses: 12),
            Step(rating: .easy, stability: 1.95486565, difficulty: 9.94368546, scheduledDays: 4, reps: 39, lapses: 12),
            Step(rating: .good, stability: 3.54359722, difficulty: 9.92897014, scheduledDays: 4, reps: 40, lapses: 12),
            Step(rating: .easy, stability: 6.92188089, difficulty: 9.89046364, scheduledDays: 7, reps: 41, lapses: 12),
            Step(rating: .again, stability: 1.10026505, difficulty: 9.94922451, scheduledDays: 1, reps: 42, lapses: 13),
            Step(rating: .again, stability: 0.32380900, difficulty: 9.96853882, scheduledDays: 1, reps: 43, lapses: 14),
            Step(rating: .good, stability: 0.75976299, difficulty: 9.95379865, scheduledDays: 3, reps: 44, lapses: 14),
            Step(rating: .easy, stability: 2.66688116, difficulty: 9.92358868, scheduledDays: 4, reps: 45, lapses: 14),
            Step(rating: .good, stability: 4.39752530, difficulty: 9.90889346, scheduledDays: 5, reps: 46, lapses: 14),
            Step(rating: .hard, stability: 5.72717217, difficulty: 9.92474760, scheduledDays: 6, reps: 47, lapses: 14),
            Step(rating: .good, stability: 8.29132426, difficulty: 9.91005122, scheduledDays: 8, reps: 48, lapses: 14),
            Step(rating: .easy, stability: 14.53948771, difficulty: 9.86522289, scheduledDays: 15, reps: 49, lapses: 14),
            Step(rating: .hard, stability: 18.03881870, difficulty: 9.89575704, scheduledDays: 18, reps: 50, lapses: 14),
        ]
        runSequence(label: "longterm50", fsrs: fsrs, steps: steps)
    }
}

// MARK: - Targeted edge scenarios

@Suite("Long sequence parity — edge scenarios")
struct EdgeSequenceParityTests {

    /// Repeated lapse-relearn cycles in basic mode. Pattern: G, G, then
    /// alternating Again/Good four times. Each Again sends the card from
    /// Review → Relearning at step 0 (10-minute relearning step). The
    /// next Good then graduates back to Review with a small FSRS
    /// interval. Tests that:
    ///   - Lapses increment monotonically on Again-on-Review
    ///   - Difficulty climbs toward 10 under repeated failures (mean
    ///     reversion is overwhelmed by the +w[6] step on Again)
    ///   - Stability collapses then recovers after each cycle
    @Test("Lapse-relearn cycle (basic mode, 10 reviews)")
    func lapseRelearnCycle() {
        let fsrs = FSRS()
        let steps: [Step] = [
            Step(rating: .good, stability: 2.30650000, difficulty: 2.11810397, scheduledDays: 0, reps: 1, lapses: 0),
            Step(rating: .good, stability: 2.30650000, difficulty: 2.11121424, scheduledDays: 2, reps: 2, lapses: 0),
            Step(rating: .again, stability: 0.60770166, difficulty: 7.39223814, scheduledDays: 0, reps: 3, lapses: 1),
            Step(rating: .good, stability: 0.65979762, difficulty: 7.38007427, scheduledDays: 1, reps: 4, lapses: 1),
            Step(rating: .again, stability: 0.23203410, difficulty: 9.12407659, scheduledDays: 0, reps: 5, lapses: 2),
            Step(rating: .good, stability: 0.26840194, difficulty: 9.11018088, scheduledDays: 1, reps: 6, lapses: 2),
            Step(rating: .again, stability: 0.11831252, difficulty: 9.69275088, scheduledDays: 0, reps: 7, lapses: 3),
            Step(rating: .good, stability: 0.14305810, difficulty: 9.67828650, scheduledDays: 1, reps: 8, lapses: 3),
            Step(rating: .again, stability: 0.07231756, difficulty: 9.87948333, scheduledDays: 0, reps: 9, lapses: 4),
            Step(rating: .good, stability: 0.09032182, difficulty: 9.86483222, scheduledDays: 1, reps: 10, lapses: 4),
        ]
        runSequence(label: "lapseRelearn", fsrs: fsrs, steps: steps)
    }

    /// Easy from a new card graduates immediately to Review with the
    /// initial S₀(.easy) = w[3] = 8.2956 → 8 days. Subsequent Easy
    /// reviews compound the easy bonus (w[16] = 1.8729). Difficulty
    /// stays clamped at 1.0 because mean-reversion + linear-damping at
    /// D=1 gives a value ≤ 1, which clamps back to 1.
    ///
    /// This tests both the new-card Easy graduation path and the recall
    /// stability formula's easy bonus over many compounded steps.
    @Test("Easy graduation from new — 5 consecutive Easy reviews (basic mode)")
    func easyGraduationCascade() {
        let fsrs = FSRS()
        let steps: [Step] = [
            Step(rating: .easy, stability: 8.29560000, difficulty: 1.00000000, scheduledDays: 8, reps: 1, lapses: 0),
            Step(rating: .easy, stability: 65.62422648, difficulty: 1.00000000, scheduledDays: 66, reps: 2, lapses: 0),
            Step(rating: .easy, stability: 396.77501923, difficulty: 1.00000000, scheduledDays: 397, reps: 3, lapses: 0),
            Step(rating: .easy, stability: 1874.91696522, difficulty: 1.00000000, scheduledDays: 1875, reps: 4, lapses: 0),
            Step(rating: .easy, stability: 7265.43276492, difficulty: 1.00000000, scheduledDays: 7265, reps: 5, lapses: 0),
        ]
        runSequence(label: "easyCascade", fsrs: fsrs, steps: steps)
    }

    /// Three sibling cards taken to Review state (long-term mode, S=2.3065,
    /// scheduledDays=3). Then each is reviewed Good at a different time
    /// relative to its due date:
    ///   - exactly at due (t = 3 days)
    ///   - 2 days early   (t = 1 day)
    ///   - 5 days late    (t = 8 days)
    ///
    /// The forgetting curve gives lower R for larger t, which feeds into
    /// the recall stability formula's spacing-effect term `(exp(w[10]×(1-R)) - 1)`.
    /// Larger t → lower R → bigger stability gain on Good.
    @Test("Review timing: at-due vs early vs overdue (long-term mode)")
    func reviewTimingVariants() {
        let fsrs = FSRS(parameters: Parameters(enableShortTerm: false))
        let baseCard = FSRS.createCard(now: refDate)
        // Bring all three siblings to the same Review state via long-term
        // Good. After this step: S=2.3065, D=2.11810397, scheduledDays=3,
        // due = refDate + 3 days.
        let warmed = fsrs.schedule(card: baseCard, now: refDate, rating: .good).card
        #expect(warmed.stability == 2.30650000)
        #expect(warmed.difficulty == 2.11810397)
        #expect(warmed.scheduledDays == 3)

        // At due (t = 3 days)
        let atDue = fsrs.schedule(
            card: warmed, now: dateAfter(days: 3), rating: .good
        ).card
        #expect(atDue.stability == 13.82690327)
        #expect(atDue.difficulty == 2.11121424)
        #expect(atDue.scheduledDays == 14)

        // 2 days early (t = 1 day): higher R, smaller stability gain
        let early = fsrs.schedule(
            card: warmed, now: dateAfter(days: 1), rating: .good
        ).card
        #expect(early.stability == 7.31530068)
        #expect(early.difficulty == 2.11121424)  // D update is t-independent
        #expect(early.scheduledDays == 7)

        // 5 days late (t = 8 days): lower R, larger stability gain
        let late = fsrs.schedule(
            card: warmed, now: dateAfter(days: 8), rating: .good
        ).card
        #expect(late.stability == 22.76818035)
        #expect(late.difficulty == 2.11121424)
        #expect(late.scheduledDays == 23)

        // Spacing-effect ordering: late > at-due > early.
        #expect(early.stability < atDue.stability)
        #expect(atDue.stability < late.stability)
    }

    /// Reproduces ts-fsrs FSRS-6.test.ts `ivl_history` test verbatim:
    /// 13 ratings G,G,G,G,G,G,A,A,G,G,G,G,G in basic mode produce
    /// scheduled_days `[0, 2, 11, 46, 163, 498, 0, 0, 2, 4, 7, 12, 21]`.
    ///
    /// This is a direct lift from the canonical ts-fsrs test suite — if
    /// any single value diverges, Swift has drifted from the reference.
    @Test("ts-fsrs FSRS-6 ivl_history reproduction (basic mode)")
    func ivlHistoryReproduction() {
        let fsrs = FSRS()
        var card = FSRS.createCard(now: refDate)
        var now = refDate
        let ratings: [Rating] = [
            .good, .good, .good, .good, .good, .good,
            .again, .again,
            .good, .good, .good, .good, .good,
        ]
        let expectedIntervals: [Int] = [0, 2, 11, 46, 163, 498, 0, 0, 2, 4, 7, 12, 21]
        var observed: [Int] = []
        for rating in ratings {
            card = fsrs.schedule(card: card, now: now, rating: rating).card
            observed.append(card.scheduledDays)
            now = card.due
        }
        #expect(observed == expectedIntervals)
    }

    /// Reproduces ts-fsrs FSRS-6.test.ts `memory state[short-term]`:
    /// ratings A,G,G,G,G,G with gaps `[0, 0, 1, 3, 8, 21]` days produce
    /// final `S ≈ 53.62691, D ≈ 6.3574867` (4-decimal tolerance in the
    /// reference test). Swift's deterministic output should land within
    /// 1e-4 of those targets — values are quoted from the reference, so
    /// any larger gap is a real divergence.
    @Test("ts-fsrs FSRS-6 memory state[short-term] reproduction")
    func memoryStateShortTerm() {
        let fsrs = FSRS()  // basic mode = enableShortTerm
        var card = FSRS.createCard(now: refDate)
        var now = refDate
        let seq: [(Rating, Int)] = [
            (.again, 0), (.good, 0), (.good, 1), (.good, 3), (.good, 8), (.good, 21),
        ]
        for (rating, gapDays) in seq {
            now = now.addingTimeInterval(Double(gapDays) * 86400.0)
            card = fsrs.schedule(card: card, now: now, rating: rating).card
        }
        // ts-fsrs uses toBeCloseTo(...4) which compares within 5e-5.
        // We assert tighter (1e-4) to leave headroom but flag any real drift.
        #expect(abs(card.stability - 53.62691) < 1e-4,
                "stability \(card.stability) ≠ 53.62691 ± 1e-4")
        #expect(abs(card.difficulty - 6.3574867) < 1e-4,
                "difficulty \(card.difficulty) ≠ 6.3574867 ± 1e-4")
    }

    /// Reproduces ts-fsrs FSRS-6.test.ts `memory state[long-term]`:
    /// same ratings + gaps as the short-term variant, but every review
    /// goes through the long-term scheduler. Final `S ≈ 53.335106,
    /// D ≈ 6.3574867`.
    @Test("ts-fsrs FSRS-6 memory state[long-term] reproduction")
    func memoryStateLongTerm() {
        let fsrs = FSRS(parameters: Parameters(enableShortTerm: false))
        var card = FSRS.createCard(now: refDate)
        var now = refDate
        let seq: [(Rating, Int)] = [
            (.again, 0), (.good, 0), (.good, 1), (.good, 3), (.good, 8), (.good, 21),
        ]
        for (rating, gapDays) in seq {
            now = now.addingTimeInterval(Double(gapDays) * 86400.0)
            card = fsrs.schedule(card: card, now: now, rating: rating).card
        }
        #expect(abs(card.stability - 53.335106) < 1e-4,
                "stability \(card.stability) ≠ 53.335106 ± 1e-4")
        #expect(abs(card.difficulty - 6.3574867) < 1e-4,
                "difficulty \(card.difficulty) ≠ 6.3574867 ± 1e-4")
    }
}
